### ISSUE TITLE
Releases and Small Request

### ISSUE THREAD

**Issue by dmhendricks** [Lewiscowles1986/WordPressSVGPlugin#19]
Greetings,

This is a great and no-nonsense plugin - I use it on several sites.

A couple of small, personal requests:

* Would you remove the `// forced crop STFU` line? I use this in production. :smirk: I remove it myself, but I have some automation scripts that pull it automatically.
* It appears that there have been several changes/fixes since the 1.6.4 release version. Would you mind doing a new release (1.6.5 or whatever appropriate) when you feel it is ready?

Thank you,
Daniel

**Comment by Lewiscowles1986** [comment]
Hi @dmhendricks,

Thanks for the issue. I've resolved both points. 

As I seem to have been lax on this plugin due to it's niche interest :smirk: I've just bumped to 1.7.0

Covers me if the API has changed at-all. 

There are other issues, I'd really appreciate help with if you're using on a number of client sites. Should be quite easy to add automated tests using phantomJS or Selenium (anything contributed to automated testing I'd be happy with as currently, I'm semi-manually testing).

Turns out none of my clients cares about using this, so my input is kinda on an as-can-be-bothered basis.

I'd also appreciate your input as a user on design decisions this plugin has made that make your life harder, improvements, breakages etc. 

Keep in contact :+1:
